<?php
/**
 * Correction
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  Hallerweb\Prioritize\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Prioritize API
 *
 * REST API of Prioritize, a resource, project and IoT orchestration platform. All endpoints live under /api/v1. From 1.0.0 on this REST surface is the stable public contract (SemVer); the Vaadin admin GUI and its @Route URLs are an implementation detail and NOT part of that promise. A few areas are marked 'experimental' in their schema and may still change within the 1.x line.
 *
 * The version of the OpenAPI document: 1.4.0
 * Contact: peter.haller@prioritize-iot.de
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.10.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Hallerweb\Prioritize\Client\Model;

use \ArrayAccess;
use \Hallerweb\Prioritize\Client\ObjectSerializer;

/**
 * Correction Class Doc Comment
 *
 * @category Class
 * @package  Hallerweb\Prioritize\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class Correction implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'Correction';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'kind' => 'string',
        'corrected_by_id' => 'int',
        'corrected_by' => 'string',
        'corrected_at' => '\DateTime',
        'reason' => 'string',
        'original_from' => '\DateTime',
        'original_until' => '\DateTime'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'kind' => null,
        'corrected_by_id' => 'int64',
        'corrected_by' => null,
        'corrected_at' => 'date-time',
        'reason' => null,
        'original_from' => 'date-time',
        'original_until' => 'date-time'
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'kind' => false,
        'corrected_by_id' => false,
        'corrected_by' => false,
        'corrected_at' => false,
        'reason' => false,
        'original_from' => false,
        'original_until' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'kind' => 'kind',
        'corrected_by_id' => 'correctedById',
        'corrected_by' => 'correctedBy',
        'corrected_at' => 'correctedAt',
        'reason' => 'reason',
        'original_from' => 'originalFrom',
        'original_until' => 'originalUntil'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'kind' => 'setKind',
        'corrected_by_id' => 'setCorrectedById',
        'corrected_by' => 'setCorrectedBy',
        'corrected_at' => 'setCorrectedAt',
        'reason' => 'setReason',
        'original_from' => 'setOriginalFrom',
        'original_until' => 'setOriginalUntil'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'kind' => 'getKind',
        'corrected_by_id' => 'getCorrectedById',
        'corrected_by' => 'getCorrectedBy',
        'corrected_at' => 'getCorrectedAt',
        'reason' => 'getReason',
        'original_from' => 'getOriginalFrom',
        'original_until' => 'getOriginalUntil'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }

    public const KIND_CORRECTED = 'CORRECTED';
    public const KIND_BACKDATED_STOP = 'BACKDATED_STOP';
    public const KIND_MANUAL_ENTRY = 'MANUAL_ENTRY';

    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getKindAllowableValues()
    {
        return [
            self::KIND_CORRECTED,
            self::KIND_BACKDATED_STOP,
            self::KIND_MANUAL_ENTRY,
        ];
    }

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->setIfExists('kind', $data ?? [], null);
        $this->setIfExists('corrected_by_id', $data ?? [], null);
        $this->setIfExists('corrected_by', $data ?? [], null);
        $this->setIfExists('corrected_at', $data ?? [], null);
        $this->setIfExists('reason', $data ?? [], null);
        $this->setIfExists('original_from', $data ?? [], null);
        $this->setIfExists('original_until', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        $allowedValues = $this->getKindAllowableValues();
        if (!is_null($this->container['kind']) && !in_array($this->container['kind'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value '%s' for 'kind', must be one of '%s'",
                $this->container['kind'],
                implode("', '", $allowedValues)
            );
        }

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets kind
     *
     * @return string|null
     */
    public function getKind()
    {
        return $this->container['kind'];
    }

    /**
     * Sets kind
     *
     * @param string|null $kind kind
     *
     * @return self
     */
    public function setKind($kind)
    {
        if (is_null($kind)) {
            throw new \InvalidArgumentException('non-nullable kind cannot be null');
        }
        $allowedValues = $this->getKindAllowableValues();
        if (!in_array($kind, $allowedValues, true)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value '%s' for 'kind', must be one of '%s'",
                    $kind,
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['kind'] = $kind;

        return $this;
    }

    /**
     * Gets corrected_by_id
     *
     * @return int|null
     */
    public function getCorrectedById()
    {
        return $this->container['corrected_by_id'];
    }

    /**
     * Sets corrected_by_id
     *
     * @param int|null $corrected_by_id corrected_by_id
     *
     * @return self
     */
    public function setCorrectedById($corrected_by_id)
    {
        if (is_null($corrected_by_id)) {
            throw new \InvalidArgumentException('non-nullable corrected_by_id cannot be null');
        }
        $this->container['corrected_by_id'] = $corrected_by_id;

        return $this;
    }

    /**
     * Gets corrected_by
     *
     * @return string|null
     */
    public function getCorrectedBy()
    {
        return $this->container['corrected_by'];
    }

    /**
     * Sets corrected_by
     *
     * @param string|null $corrected_by corrected_by
     *
     * @return self
     */
    public function setCorrectedBy($corrected_by)
    {
        if (is_null($corrected_by)) {
            throw new \InvalidArgumentException('non-nullable corrected_by cannot be null');
        }
        $this->container['corrected_by'] = $corrected_by;

        return $this;
    }

    /**
     * Gets corrected_at
     *
     * @return \DateTime|null
     */
    public function getCorrectedAt()
    {
        return $this->container['corrected_at'];
    }

    /**
     * Sets corrected_at
     *
     * @param \DateTime|null $corrected_at corrected_at
     *
     * @return self
     */
    public function setCorrectedAt($corrected_at)
    {
        if (is_null($corrected_at)) {
            throw new \InvalidArgumentException('non-nullable corrected_at cannot be null');
        }
        $this->container['corrected_at'] = $corrected_at;

        return $this;
    }

    /**
     * Gets reason
     *
     * @return string|null
     */
    public function getReason()
    {
        return $this->container['reason'];
    }

    /**
     * Sets reason
     *
     * @param string|null $reason reason
     *
     * @return self
     */
    public function setReason($reason)
    {
        if (is_null($reason)) {
            throw new \InvalidArgumentException('non-nullable reason cannot be null');
        }
        $this->container['reason'] = $reason;

        return $this;
    }

    /**
     * Gets original_from
     *
     * @return \DateTime|null
     */
    public function getOriginalFrom()
    {
        return $this->container['original_from'];
    }

    /**
     * Sets original_from
     *
     * @param \DateTime|null $original_from original_from
     *
     * @return self
     */
    public function setOriginalFrom($original_from)
    {
        if (is_null($original_from)) {
            throw new \InvalidArgumentException('non-nullable original_from cannot be null');
        }
        $this->container['original_from'] = $original_from;

        return $this;
    }

    /**
     * Gets original_until
     *
     * @return \DateTime|null
     */
    public function getOriginalUntil()
    {
        return $this->container['original_until'];
    }

    /**
     * Sets original_until
     *
     * @param \DateTime|null $original_until original_until
     *
     * @return self
     */
    public function setOriginalUntil($original_until)
    {
        if (is_null($original_until)) {
            throw new \InvalidArgumentException('non-nullable original_until cannot be null');
        }
        $this->container['original_until'] = $original_until;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


