<?php
/**
 * TrackingSummary
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  Hallerweb\Prioritize\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Prioritize API
 *
 * REST API of Prioritize, a resource, project and IoT orchestration platform. All endpoints live under /api/v1. From 1.0.0 on this REST surface is the stable public contract (SemVer); the Vaadin admin GUI and its @Route URLs are an implementation detail and NOT part of that promise. A few areas are marked 'experimental' in their schema and may still change within the 1.x line.
 *
 * The version of the OpenAPI document: 1.4.0
 * Contact: peter.haller@prioritize-iot.de
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.10.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Hallerweb\Prioritize\Client\Model;

use \ArrayAccess;
use \Hallerweb\Prioritize\Client\ObjectSerializer;

/**
 * TrackingSummary Class Doc Comment
 *
 * @category Class
 * @package  Hallerweb\Prioritize\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class TrackingSummary implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'TrackingSummary';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'task_id' => 'int',
        'tracking_for_me' => 'bool',
        'running_count' => 'int',
        'total_seconds' => 'int',
        'total_text' => 'string',
        'running_since' => '\DateTime'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'task_id' => 'int64',
        'tracking_for_me' => null,
        'running_count' => 'int32',
        'total_seconds' => 'int64',
        'total_text' => null,
        'running_since' => 'date-time'
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'task_id' => false,
        'tracking_for_me' => false,
        'running_count' => false,
        'total_seconds' => false,
        'total_text' => false,
        'running_since' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'task_id' => 'taskId',
        'tracking_for_me' => 'trackingForMe',
        'running_count' => 'runningCount',
        'total_seconds' => 'totalSeconds',
        'total_text' => 'totalText',
        'running_since' => 'runningSince'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'task_id' => 'setTaskId',
        'tracking_for_me' => 'setTrackingForMe',
        'running_count' => 'setRunningCount',
        'total_seconds' => 'setTotalSeconds',
        'total_text' => 'setTotalText',
        'running_since' => 'setRunningSince'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'task_id' => 'getTaskId',
        'tracking_for_me' => 'getTrackingForMe',
        'running_count' => 'getRunningCount',
        'total_seconds' => 'getTotalSeconds',
        'total_text' => 'getTotalText',
        'running_since' => 'getRunningSince'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->setIfExists('task_id', $data ?? [], null);
        $this->setIfExists('tracking_for_me', $data ?? [], null);
        $this->setIfExists('running_count', $data ?? [], null);
        $this->setIfExists('total_seconds', $data ?? [], null);
        $this->setIfExists('total_text', $data ?? [], null);
        $this->setIfExists('running_since', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets task_id
     *
     * @return int|null
     */
    public function getTaskId()
    {
        return $this->container['task_id'];
    }

    /**
     * Sets task_id
     *
     * @param int|null $task_id task_id
     *
     * @return self
     */
    public function setTaskId($task_id)
    {
        if (is_null($task_id)) {
            throw new \InvalidArgumentException('non-nullable task_id cannot be null');
        }
        $this->container['task_id'] = $task_id;

        return $this;
    }

    /**
     * Gets tracking_for_me
     *
     * @return bool|null
     */
    public function getTrackingForMe()
    {
        return $this->container['tracking_for_me'];
    }

    /**
     * Sets tracking_for_me
     *
     * @param bool|null $tracking_for_me tracking_for_me
     *
     * @return self
     */
    public function setTrackingForMe($tracking_for_me)
    {
        if (is_null($tracking_for_me)) {
            throw new \InvalidArgumentException('non-nullable tracking_for_me cannot be null');
        }
        $this->container['tracking_for_me'] = $tracking_for_me;

        return $this;
    }

    /**
     * Gets running_count
     *
     * @return int|null
     */
    public function getRunningCount()
    {
        return $this->container['running_count'];
    }

    /**
     * Sets running_count
     *
     * @param int|null $running_count running_count
     *
     * @return self
     */
    public function setRunningCount($running_count)
    {
        if (is_null($running_count)) {
            throw new \InvalidArgumentException('non-nullable running_count cannot be null');
        }
        $this->container['running_count'] = $running_count;

        return $this;
    }

    /**
     * Gets total_seconds
     *
     * @return int|null
     */
    public function getTotalSeconds()
    {
        return $this->container['total_seconds'];
    }

    /**
     * Sets total_seconds
     *
     * @param int|null $total_seconds total_seconds
     *
     * @return self
     */
    public function setTotalSeconds($total_seconds)
    {
        if (is_null($total_seconds)) {
            throw new \InvalidArgumentException('non-nullable total_seconds cannot be null');
        }
        $this->container['total_seconds'] = $total_seconds;

        return $this;
    }

    /**
     * Gets total_text
     *
     * @return string|null
     */
    public function getTotalText()
    {
        return $this->container['total_text'];
    }

    /**
     * Sets total_text
     *
     * @param string|null $total_text total_text
     *
     * @return self
     */
    public function setTotalText($total_text)
    {
        if (is_null($total_text)) {
            throw new \InvalidArgumentException('non-nullable total_text cannot be null');
        }
        $this->container['total_text'] = $total_text;

        return $this;
    }

    /**
     * Gets running_since
     *
     * @return \DateTime|null
     */
    public function getRunningSince()
    {
        return $this->container['running_since'];
    }

    /**
     * Sets running_since
     *
     * @param \DateTime|null $running_since running_since
     *
     * @return self
     */
    public function setRunningSince($running_since)
    {
        if (is_null($running_since)) {
            throw new \InvalidArgumentException('non-nullable running_since cannot be null');
        }
        $this->container['running_since'] = $running_since;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


