<?php
/**
 * ProjectGoalsApi
 * PHP version 7.4
 *
 * @category Class
 * @package  Hallerweb\Prioritize\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Prioritize API
 *
 * REST API of Prioritize, a resource, project and IoT orchestration platform. All endpoints live under /api/v1. From 1.0.0 on this REST surface is the stable public contract (SemVer); the Vaadin admin GUI and its @Route URLs are an implementation detail and NOT part of that promise. A few areas are marked 'experimental' in their schema and may still change within the 1.x line.
 *
 * The version of the OpenAPI document: 1.4.0
 * Contact: peter.haller@prioritize-iot.de
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.10.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Hallerweb\Prioritize\Client\Api;

use GuzzleHttp\Client;
use GuzzleHttp\ClientInterface;
use GuzzleHttp\Exception\ConnectException;
use GuzzleHttp\Exception\RequestException;
use GuzzleHttp\Psr7\MultipartStream;
use GuzzleHttp\Psr7\Request;
use GuzzleHttp\RequestOptions;
use Hallerweb\Prioritize\Client\ApiException;
use Hallerweb\Prioritize\Client\Configuration;
use Hallerweb\Prioritize\Client\HeaderSelector;
use Hallerweb\Prioritize\Client\ObjectSerializer;

/**
 * ProjectGoalsApi Class Doc Comment
 *
 * @category Class
 * @package  Hallerweb\Prioritize\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class ProjectGoalsApi
{
    /**
     * @var ClientInterface
     */
    protected $client;

    /**
     * @var Configuration
     */
    protected $config;

    /**
     * @var HeaderSelector
     */
    protected $headerSelector;

    /**
     * @var int Host index
     */
    protected $hostIndex;

    /** @var string[] $contentTypes **/
    public const contentTypes = [
        'projectGoalCreateGoal' => [
            'application/json',
        ],
        'projectGoalDeleteGoal' => [
            'application/json',
        ],
        'projectGoalGetGoal' => [
            'application/json',
        ],
        'projectGoalGetGoals' => [
            'application/json',
        ],
        'projectGoalGetProgress' => [
            'application/json',
        ],
        'projectGoalUpdateGoal' => [
            'application/json',
        ],
    ];

    /**
     * @param ClientInterface $client
     * @param Configuration   $config
     * @param HeaderSelector  $selector
     * @param int             $hostIndex (Optional) host index to select the list of hosts if defined in the OpenAPI spec
     */
    public function __construct(
        ClientInterface $client = null,
        Configuration $config = null,
        HeaderSelector $selector = null,
        $hostIndex = 0
    ) {
        $this->client = $client ?: new Client();
        $this->config = $config ?: Configuration::getDefaultConfiguration();
        $this->headerSelector = $selector ?: new HeaderSelector();
        $this->hostIndex = $hostIndex;
    }

    /**
     * Set the host index
     *
     * @param int $hostIndex Host index (required)
     */
    public function setHostIndex($hostIndex): void
    {
        $this->hostIndex = $hostIndex;
    }

    /**
     * Get the host index
     *
     * @return int Host index
     */
    public function getHostIndex()
    {
        return $this->hostIndex;
    }

    /**
     * @return Configuration
     */
    public function getConfig()
    {
        return $this->config;
    }

    /**
     * Operation projectGoalCreateGoal
     *
     * Create goal
     *
     * @param  int $project_id project_id (required)
     * @param  \Hallerweb\Prioritize\Client\Model\GoalRequest $goal_request goal_request (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['projectGoalCreateGoal'] to see the possible values for this operation
     *
     * @throws \Hallerweb\Prioritize\Client\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \Hallerweb\Prioritize\Client\Model\ProjectGoalDTO
     */
    public function projectGoalCreateGoal($project_id, $goal_request, string $contentType = self::contentTypes['projectGoalCreateGoal'][0])
    {
        list($response) = $this->projectGoalCreateGoalWithHttpInfo($project_id, $goal_request, $contentType);
        return $response;
    }

    /**
     * Operation projectGoalCreateGoalWithHttpInfo
     *
     * Create goal
     *
     * @param  int $project_id (required)
     * @param  \Hallerweb\Prioritize\Client\Model\GoalRequest $goal_request (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['projectGoalCreateGoal'] to see the possible values for this operation
     *
     * @throws \Hallerweb\Prioritize\Client\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \Hallerweb\Prioritize\Client\Model\ProjectGoalDTO, HTTP status code, HTTP response headers (array of strings)
     */
    public function projectGoalCreateGoalWithHttpInfo($project_id, $goal_request, string $contentType = self::contentTypes['projectGoalCreateGoal'][0])
    {
        $request = $this->projectGoalCreateGoalRequest($project_id, $goal_request, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 200:
                    if ('\Hallerweb\Prioritize\Client\Model\ProjectGoalDTO' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ('\Hallerweb\Prioritize\Client\Model\ProjectGoalDTO' !== 'string') {
                            try {
                                $content = json_decode($content, false, 512, JSON_THROW_ON_ERROR);
                            } catch (\JsonException $exception) {
                                throw new ApiException(
                                    sprintf(
                                        'Error JSON decoding server response (%s)',
                                        $request->getUri()
                                    ),
                                    $statusCode,
                                    $response->getHeaders(),
                                    $content
                                );
                            }
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\Hallerweb\Prioritize\Client\Model\ProjectGoalDTO', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
            }

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            $returnType = '\Hallerweb\Prioritize\Client\Model\ProjectGoalDTO';
            if ($returnType === '\SplFileObject') {
                $content = $response->getBody(); //stream goes to serializer
            } else {
                $content = (string) $response->getBody();
                if ($returnType !== 'string') {
                    try {
                        $content = json_decode($content, false, 512, JSON_THROW_ON_ERROR);
                    } catch (\JsonException $exception) {
                        throw new ApiException(
                            sprintf(
                                'Error JSON decoding server response (%s)',
                                $request->getUri()
                            ),
                            $statusCode,
                            $response->getHeaders(),
                            $content
                        );
                    }
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Hallerweb\Prioritize\Client\Model\ProjectGoalDTO',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation projectGoalCreateGoalAsync
     *
     * Create goal
     *
     * @param  int $project_id (required)
     * @param  \Hallerweb\Prioritize\Client\Model\GoalRequest $goal_request (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['projectGoalCreateGoal'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function projectGoalCreateGoalAsync($project_id, $goal_request, string $contentType = self::contentTypes['projectGoalCreateGoal'][0])
    {
        return $this->projectGoalCreateGoalAsyncWithHttpInfo($project_id, $goal_request, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation projectGoalCreateGoalAsyncWithHttpInfo
     *
     * Create goal
     *
     * @param  int $project_id (required)
     * @param  \Hallerweb\Prioritize\Client\Model\GoalRequest $goal_request (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['projectGoalCreateGoal'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function projectGoalCreateGoalAsyncWithHttpInfo($project_id, $goal_request, string $contentType = self::contentTypes['projectGoalCreateGoal'][0])
    {
        $returnType = '\Hallerweb\Prioritize\Client\Model\ProjectGoalDTO';
        $request = $this->projectGoalCreateGoalRequest($project_id, $goal_request, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'projectGoalCreateGoal'
     *
     * @param  int $project_id (required)
     * @param  \Hallerweb\Prioritize\Client\Model\GoalRequest $goal_request (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['projectGoalCreateGoal'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function projectGoalCreateGoalRequest($project_id, $goal_request, string $contentType = self::contentTypes['projectGoalCreateGoal'][0])
    {

        // verify the required parameter 'project_id' is set
        if ($project_id === null || (is_array($project_id) && count($project_id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $project_id when calling projectGoalCreateGoal'
            );
        }

        // verify the required parameter 'goal_request' is set
        if ($goal_request === null || (is_array($goal_request) && count($goal_request) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $goal_request when calling projectGoalCreateGoal'
            );
        }


        $resourcePath = '/api/v1/projects/{projectId}/goals';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;



        // path params
        if ($project_id !== null) {
            $resourcePath = str_replace(
                '{' . 'projectId' . '}',
                ObjectSerializer::toPathValue($project_id),
                $resourcePath
            );
        }


        $headers = $this->headerSelector->selectHeaders(
            ['*/*', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (isset($goal_request)) {
            if (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the body
                $httpBody = \GuzzleHttp\Utils::jsonEncode(ObjectSerializer::sanitizeForSerialization($goal_request));
            } else {
                $httpBody = $goal_request;
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires HTTP basic authentication
        if (!empty($this->config->getUsername()) || !(empty($this->config->getPassword()))) {
            $headers['Authorization'] = 'Basic ' . base64_encode($this->config->getUsername() . ":" . $this->config->getPassword());
        }
        // this endpoint requires Bearer (JWT) authentication (access token)
        if (!empty($this->config->getAccessToken())) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'POST',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation projectGoalDeleteGoal
     *
     * Delete goal
     *
     * @param  int $project_id project_id (required)
     * @param  int $goal_id goal_id (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['projectGoalDeleteGoal'] to see the possible values for this operation
     *
     * @throws \Hallerweb\Prioritize\Client\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return void
     */
    public function projectGoalDeleteGoal($project_id, $goal_id, string $contentType = self::contentTypes['projectGoalDeleteGoal'][0])
    {
        $this->projectGoalDeleteGoalWithHttpInfo($project_id, $goal_id, $contentType);
    }

    /**
     * Operation projectGoalDeleteGoalWithHttpInfo
     *
     * Delete goal
     *
     * @param  int $project_id (required)
     * @param  int $goal_id (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['projectGoalDeleteGoal'] to see the possible values for this operation
     *
     * @throws \Hallerweb\Prioritize\Client\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of null, HTTP status code, HTTP response headers (array of strings)
     */
    public function projectGoalDeleteGoalWithHttpInfo($project_id, $goal_id, string $contentType = self::contentTypes['projectGoalDeleteGoal'][0])
    {
        $request = $this->projectGoalDeleteGoalRequest($project_id, $goal_id, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            return [null, $statusCode, $response->getHeaders()];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
            }
            throw $e;
        }
    }

    /**
     * Operation projectGoalDeleteGoalAsync
     *
     * Delete goal
     *
     * @param  int $project_id (required)
     * @param  int $goal_id (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['projectGoalDeleteGoal'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function projectGoalDeleteGoalAsync($project_id, $goal_id, string $contentType = self::contentTypes['projectGoalDeleteGoal'][0])
    {
        return $this->projectGoalDeleteGoalAsyncWithHttpInfo($project_id, $goal_id, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation projectGoalDeleteGoalAsyncWithHttpInfo
     *
     * Delete goal
     *
     * @param  int $project_id (required)
     * @param  int $goal_id (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['projectGoalDeleteGoal'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function projectGoalDeleteGoalAsyncWithHttpInfo($project_id, $goal_id, string $contentType = self::contentTypes['projectGoalDeleteGoal'][0])
    {
        $returnType = '';
        $request = $this->projectGoalDeleteGoalRequest($project_id, $goal_id, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    return [null, $response->getStatusCode(), $response->getHeaders()];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'projectGoalDeleteGoal'
     *
     * @param  int $project_id (required)
     * @param  int $goal_id (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['projectGoalDeleteGoal'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function projectGoalDeleteGoalRequest($project_id, $goal_id, string $contentType = self::contentTypes['projectGoalDeleteGoal'][0])
    {

        // verify the required parameter 'project_id' is set
        if ($project_id === null || (is_array($project_id) && count($project_id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $project_id when calling projectGoalDeleteGoal'
            );
        }

        // verify the required parameter 'goal_id' is set
        if ($goal_id === null || (is_array($goal_id) && count($goal_id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $goal_id when calling projectGoalDeleteGoal'
            );
        }


        $resourcePath = '/api/v1/projects/{projectId}/goals/{goalId}';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;



        // path params
        if ($project_id !== null) {
            $resourcePath = str_replace(
                '{' . 'projectId' . '}',
                ObjectSerializer::toPathValue($project_id),
                $resourcePath
            );
        }
        // path params
        if ($goal_id !== null) {
            $resourcePath = str_replace(
                '{' . 'goalId' . '}',
                ObjectSerializer::toPathValue($goal_id),
                $resourcePath
            );
        }


        $headers = $this->headerSelector->selectHeaders(
            [],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires HTTP basic authentication
        if (!empty($this->config->getUsername()) || !(empty($this->config->getPassword()))) {
            $headers['Authorization'] = 'Basic ' . base64_encode($this->config->getUsername() . ":" . $this->config->getPassword());
        }
        // this endpoint requires Bearer (JWT) authentication (access token)
        if (!empty($this->config->getAccessToken())) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'DELETE',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation projectGoalGetGoal
     *
     * Get goal
     *
     * @param  int $project_id project_id (required)
     * @param  int $goal_id goal_id (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['projectGoalGetGoal'] to see the possible values for this operation
     *
     * @throws \Hallerweb\Prioritize\Client\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \Hallerweb\Prioritize\Client\Model\ProjectGoalDTO
     */
    public function projectGoalGetGoal($project_id, $goal_id, string $contentType = self::contentTypes['projectGoalGetGoal'][0])
    {
        list($response) = $this->projectGoalGetGoalWithHttpInfo($project_id, $goal_id, $contentType);
        return $response;
    }

    /**
     * Operation projectGoalGetGoalWithHttpInfo
     *
     * Get goal
     *
     * @param  int $project_id (required)
     * @param  int $goal_id (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['projectGoalGetGoal'] to see the possible values for this operation
     *
     * @throws \Hallerweb\Prioritize\Client\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \Hallerweb\Prioritize\Client\Model\ProjectGoalDTO, HTTP status code, HTTP response headers (array of strings)
     */
    public function projectGoalGetGoalWithHttpInfo($project_id, $goal_id, string $contentType = self::contentTypes['projectGoalGetGoal'][0])
    {
        $request = $this->projectGoalGetGoalRequest($project_id, $goal_id, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 200:
                    if ('\Hallerweb\Prioritize\Client\Model\ProjectGoalDTO' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ('\Hallerweb\Prioritize\Client\Model\ProjectGoalDTO' !== 'string') {
                            try {
                                $content = json_decode($content, false, 512, JSON_THROW_ON_ERROR);
                            } catch (\JsonException $exception) {
                                throw new ApiException(
                                    sprintf(
                                        'Error JSON decoding server response (%s)',
                                        $request->getUri()
                                    ),
                                    $statusCode,
                                    $response->getHeaders(),
                                    $content
                                );
                            }
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\Hallerweb\Prioritize\Client\Model\ProjectGoalDTO', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
            }

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            $returnType = '\Hallerweb\Prioritize\Client\Model\ProjectGoalDTO';
            if ($returnType === '\SplFileObject') {
                $content = $response->getBody(); //stream goes to serializer
            } else {
                $content = (string) $response->getBody();
                if ($returnType !== 'string') {
                    try {
                        $content = json_decode($content, false, 512, JSON_THROW_ON_ERROR);
                    } catch (\JsonException $exception) {
                        throw new ApiException(
                            sprintf(
                                'Error JSON decoding server response (%s)',
                                $request->getUri()
                            ),
                            $statusCode,
                            $response->getHeaders(),
                            $content
                        );
                    }
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Hallerweb\Prioritize\Client\Model\ProjectGoalDTO',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation projectGoalGetGoalAsync
     *
     * Get goal
     *
     * @param  int $project_id (required)
     * @param  int $goal_id (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['projectGoalGetGoal'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function projectGoalGetGoalAsync($project_id, $goal_id, string $contentType = self::contentTypes['projectGoalGetGoal'][0])
    {
        return $this->projectGoalGetGoalAsyncWithHttpInfo($project_id, $goal_id, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation projectGoalGetGoalAsyncWithHttpInfo
     *
     * Get goal
     *
     * @param  int $project_id (required)
     * @param  int $goal_id (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['projectGoalGetGoal'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function projectGoalGetGoalAsyncWithHttpInfo($project_id, $goal_id, string $contentType = self::contentTypes['projectGoalGetGoal'][0])
    {
        $returnType = '\Hallerweb\Prioritize\Client\Model\ProjectGoalDTO';
        $request = $this->projectGoalGetGoalRequest($project_id, $goal_id, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'projectGoalGetGoal'
     *
     * @param  int $project_id (required)
     * @param  int $goal_id (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['projectGoalGetGoal'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function projectGoalGetGoalRequest($project_id, $goal_id, string $contentType = self::contentTypes['projectGoalGetGoal'][0])
    {

        // verify the required parameter 'project_id' is set
        if ($project_id === null || (is_array($project_id) && count($project_id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $project_id when calling projectGoalGetGoal'
            );
        }

        // verify the required parameter 'goal_id' is set
        if ($goal_id === null || (is_array($goal_id) && count($goal_id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $goal_id when calling projectGoalGetGoal'
            );
        }


        $resourcePath = '/api/v1/projects/{projectId}/goals/{goalId}';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;



        // path params
        if ($project_id !== null) {
            $resourcePath = str_replace(
                '{' . 'projectId' . '}',
                ObjectSerializer::toPathValue($project_id),
                $resourcePath
            );
        }
        // path params
        if ($goal_id !== null) {
            $resourcePath = str_replace(
                '{' . 'goalId' . '}',
                ObjectSerializer::toPathValue($goal_id),
                $resourcePath
            );
        }


        $headers = $this->headerSelector->selectHeaders(
            ['*/*', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires HTTP basic authentication
        if (!empty($this->config->getUsername()) || !(empty($this->config->getPassword()))) {
            $headers['Authorization'] = 'Basic ' . base64_encode($this->config->getUsername() . ":" . $this->config->getPassword());
        }
        // this endpoint requires Bearer (JWT) authentication (access token)
        if (!empty($this->config->getAccessToken())) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'GET',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation projectGoalGetGoals
     *
     * Get goals
     *
     * @param  int $project_id project_id (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['projectGoalGetGoals'] to see the possible values for this operation
     *
     * @throws \Hallerweb\Prioritize\Client\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \Hallerweb\Prioritize\Client\Model\ProjectGoalDTO[]
     */
    public function projectGoalGetGoals($project_id, string $contentType = self::contentTypes['projectGoalGetGoals'][0])
    {
        list($response) = $this->projectGoalGetGoalsWithHttpInfo($project_id, $contentType);
        return $response;
    }

    /**
     * Operation projectGoalGetGoalsWithHttpInfo
     *
     * Get goals
     *
     * @param  int $project_id (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['projectGoalGetGoals'] to see the possible values for this operation
     *
     * @throws \Hallerweb\Prioritize\Client\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \Hallerweb\Prioritize\Client\Model\ProjectGoalDTO[], HTTP status code, HTTP response headers (array of strings)
     */
    public function projectGoalGetGoalsWithHttpInfo($project_id, string $contentType = self::contentTypes['projectGoalGetGoals'][0])
    {
        $request = $this->projectGoalGetGoalsRequest($project_id, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 200:
                    if ('\Hallerweb\Prioritize\Client\Model\ProjectGoalDTO[]' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ('\Hallerweb\Prioritize\Client\Model\ProjectGoalDTO[]' !== 'string') {
                            try {
                                $content = json_decode($content, false, 512, JSON_THROW_ON_ERROR);
                            } catch (\JsonException $exception) {
                                throw new ApiException(
                                    sprintf(
                                        'Error JSON decoding server response (%s)',
                                        $request->getUri()
                                    ),
                                    $statusCode,
                                    $response->getHeaders(),
                                    $content
                                );
                            }
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\Hallerweb\Prioritize\Client\Model\ProjectGoalDTO[]', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
            }

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            $returnType = '\Hallerweb\Prioritize\Client\Model\ProjectGoalDTO[]';
            if ($returnType === '\SplFileObject') {
                $content = $response->getBody(); //stream goes to serializer
            } else {
                $content = (string) $response->getBody();
                if ($returnType !== 'string') {
                    try {
                        $content = json_decode($content, false, 512, JSON_THROW_ON_ERROR);
                    } catch (\JsonException $exception) {
                        throw new ApiException(
                            sprintf(
                                'Error JSON decoding server response (%s)',
                                $request->getUri()
                            ),
                            $statusCode,
                            $response->getHeaders(),
                            $content
                        );
                    }
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Hallerweb\Prioritize\Client\Model\ProjectGoalDTO[]',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation projectGoalGetGoalsAsync
     *
     * Get goals
     *
     * @param  int $project_id (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['projectGoalGetGoals'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function projectGoalGetGoalsAsync($project_id, string $contentType = self::contentTypes['projectGoalGetGoals'][0])
    {
        return $this->projectGoalGetGoalsAsyncWithHttpInfo($project_id, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation projectGoalGetGoalsAsyncWithHttpInfo
     *
     * Get goals
     *
     * @param  int $project_id (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['projectGoalGetGoals'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function projectGoalGetGoalsAsyncWithHttpInfo($project_id, string $contentType = self::contentTypes['projectGoalGetGoals'][0])
    {
        $returnType = '\Hallerweb\Prioritize\Client\Model\ProjectGoalDTO[]';
        $request = $this->projectGoalGetGoalsRequest($project_id, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'projectGoalGetGoals'
     *
     * @param  int $project_id (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['projectGoalGetGoals'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function projectGoalGetGoalsRequest($project_id, string $contentType = self::contentTypes['projectGoalGetGoals'][0])
    {

        // verify the required parameter 'project_id' is set
        if ($project_id === null || (is_array($project_id) && count($project_id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $project_id when calling projectGoalGetGoals'
            );
        }


        $resourcePath = '/api/v1/projects/{projectId}/goals';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;



        // path params
        if ($project_id !== null) {
            $resourcePath = str_replace(
                '{' . 'projectId' . '}',
                ObjectSerializer::toPathValue($project_id),
                $resourcePath
            );
        }


        $headers = $this->headerSelector->selectHeaders(
            ['*/*', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires HTTP basic authentication
        if (!empty($this->config->getUsername()) || !(empty($this->config->getPassword()))) {
            $headers['Authorization'] = 'Basic ' . base64_encode($this->config->getUsername() . ":" . $this->config->getPassword());
        }
        // this endpoint requires Bearer (JWT) authentication (access token)
        if (!empty($this->config->getAccessToken())) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'GET',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation projectGoalGetProgress
     *
     * Returns the project&#39;s progress derived from its goals and their tasks
     *
     * @param  int $project_id project_id (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['projectGoalGetProgress'] to see the possible values for this operation
     *
     * @throws \Hallerweb\Prioritize\Client\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \Hallerweb\Prioritize\Client\Model\ProjectProgress
     */
    public function projectGoalGetProgress($project_id, string $contentType = self::contentTypes['projectGoalGetProgress'][0])
    {
        list($response) = $this->projectGoalGetProgressWithHttpInfo($project_id, $contentType);
        return $response;
    }

    /**
     * Operation projectGoalGetProgressWithHttpInfo
     *
     * Returns the project&#39;s progress derived from its goals and their tasks
     *
     * @param  int $project_id (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['projectGoalGetProgress'] to see the possible values for this operation
     *
     * @throws \Hallerweb\Prioritize\Client\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \Hallerweb\Prioritize\Client\Model\ProjectProgress, HTTP status code, HTTP response headers (array of strings)
     */
    public function projectGoalGetProgressWithHttpInfo($project_id, string $contentType = self::contentTypes['projectGoalGetProgress'][0])
    {
        $request = $this->projectGoalGetProgressRequest($project_id, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 200:
                    if ('\Hallerweb\Prioritize\Client\Model\ProjectProgress' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ('\Hallerweb\Prioritize\Client\Model\ProjectProgress' !== 'string') {
                            try {
                                $content = json_decode($content, false, 512, JSON_THROW_ON_ERROR);
                            } catch (\JsonException $exception) {
                                throw new ApiException(
                                    sprintf(
                                        'Error JSON decoding server response (%s)',
                                        $request->getUri()
                                    ),
                                    $statusCode,
                                    $response->getHeaders(),
                                    $content
                                );
                            }
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\Hallerweb\Prioritize\Client\Model\ProjectProgress', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
            }

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            $returnType = '\Hallerweb\Prioritize\Client\Model\ProjectProgress';
            if ($returnType === '\SplFileObject') {
                $content = $response->getBody(); //stream goes to serializer
            } else {
                $content = (string) $response->getBody();
                if ($returnType !== 'string') {
                    try {
                        $content = json_decode($content, false, 512, JSON_THROW_ON_ERROR);
                    } catch (\JsonException $exception) {
                        throw new ApiException(
                            sprintf(
                                'Error JSON decoding server response (%s)',
                                $request->getUri()
                            ),
                            $statusCode,
                            $response->getHeaders(),
                            $content
                        );
                    }
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Hallerweb\Prioritize\Client\Model\ProjectProgress',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation projectGoalGetProgressAsync
     *
     * Returns the project&#39;s progress derived from its goals and their tasks
     *
     * @param  int $project_id (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['projectGoalGetProgress'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function projectGoalGetProgressAsync($project_id, string $contentType = self::contentTypes['projectGoalGetProgress'][0])
    {
        return $this->projectGoalGetProgressAsyncWithHttpInfo($project_id, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation projectGoalGetProgressAsyncWithHttpInfo
     *
     * Returns the project&#39;s progress derived from its goals and their tasks
     *
     * @param  int $project_id (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['projectGoalGetProgress'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function projectGoalGetProgressAsyncWithHttpInfo($project_id, string $contentType = self::contentTypes['projectGoalGetProgress'][0])
    {
        $returnType = '\Hallerweb\Prioritize\Client\Model\ProjectProgress';
        $request = $this->projectGoalGetProgressRequest($project_id, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'projectGoalGetProgress'
     *
     * @param  int $project_id (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['projectGoalGetProgress'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function projectGoalGetProgressRequest($project_id, string $contentType = self::contentTypes['projectGoalGetProgress'][0])
    {

        // verify the required parameter 'project_id' is set
        if ($project_id === null || (is_array($project_id) && count($project_id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $project_id when calling projectGoalGetProgress'
            );
        }


        $resourcePath = '/api/v1/projects/{projectId}/progress';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;



        // path params
        if ($project_id !== null) {
            $resourcePath = str_replace(
                '{' . 'projectId' . '}',
                ObjectSerializer::toPathValue($project_id),
                $resourcePath
            );
        }


        $headers = $this->headerSelector->selectHeaders(
            ['*/*', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires HTTP basic authentication
        if (!empty($this->config->getUsername()) || !(empty($this->config->getPassword()))) {
            $headers['Authorization'] = 'Basic ' . base64_encode($this->config->getUsername() . ":" . $this->config->getPassword());
        }
        // this endpoint requires Bearer (JWT) authentication (access token)
        if (!empty($this->config->getAccessToken())) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'GET',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation projectGoalUpdateGoal
     *
     * Update goal
     *
     * @param  int $project_id project_id (required)
     * @param  int $goal_id goal_id (required)
     * @param  \Hallerweb\Prioritize\Client\Model\GoalRequest $goal_request goal_request (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['projectGoalUpdateGoal'] to see the possible values for this operation
     *
     * @throws \Hallerweb\Prioritize\Client\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \Hallerweb\Prioritize\Client\Model\ProjectGoalDTO
     */
    public function projectGoalUpdateGoal($project_id, $goal_id, $goal_request, string $contentType = self::contentTypes['projectGoalUpdateGoal'][0])
    {
        list($response) = $this->projectGoalUpdateGoalWithHttpInfo($project_id, $goal_id, $goal_request, $contentType);
        return $response;
    }

    /**
     * Operation projectGoalUpdateGoalWithHttpInfo
     *
     * Update goal
     *
     * @param  int $project_id (required)
     * @param  int $goal_id (required)
     * @param  \Hallerweb\Prioritize\Client\Model\GoalRequest $goal_request (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['projectGoalUpdateGoal'] to see the possible values for this operation
     *
     * @throws \Hallerweb\Prioritize\Client\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \Hallerweb\Prioritize\Client\Model\ProjectGoalDTO, HTTP status code, HTTP response headers (array of strings)
     */
    public function projectGoalUpdateGoalWithHttpInfo($project_id, $goal_id, $goal_request, string $contentType = self::contentTypes['projectGoalUpdateGoal'][0])
    {
        $request = $this->projectGoalUpdateGoalRequest($project_id, $goal_id, $goal_request, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 200:
                    if ('\Hallerweb\Prioritize\Client\Model\ProjectGoalDTO' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ('\Hallerweb\Prioritize\Client\Model\ProjectGoalDTO' !== 'string') {
                            try {
                                $content = json_decode($content, false, 512, JSON_THROW_ON_ERROR);
                            } catch (\JsonException $exception) {
                                throw new ApiException(
                                    sprintf(
                                        'Error JSON decoding server response (%s)',
                                        $request->getUri()
                                    ),
                                    $statusCode,
                                    $response->getHeaders(),
                                    $content
                                );
                            }
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\Hallerweb\Prioritize\Client\Model\ProjectGoalDTO', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
            }

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            $returnType = '\Hallerweb\Prioritize\Client\Model\ProjectGoalDTO';
            if ($returnType === '\SplFileObject') {
                $content = $response->getBody(); //stream goes to serializer
            } else {
                $content = (string) $response->getBody();
                if ($returnType !== 'string') {
                    try {
                        $content = json_decode($content, false, 512, JSON_THROW_ON_ERROR);
                    } catch (\JsonException $exception) {
                        throw new ApiException(
                            sprintf(
                                'Error JSON decoding server response (%s)',
                                $request->getUri()
                            ),
                            $statusCode,
                            $response->getHeaders(),
                            $content
                        );
                    }
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Hallerweb\Prioritize\Client\Model\ProjectGoalDTO',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation projectGoalUpdateGoalAsync
     *
     * Update goal
     *
     * @param  int $project_id (required)
     * @param  int $goal_id (required)
     * @param  \Hallerweb\Prioritize\Client\Model\GoalRequest $goal_request (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['projectGoalUpdateGoal'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function projectGoalUpdateGoalAsync($project_id, $goal_id, $goal_request, string $contentType = self::contentTypes['projectGoalUpdateGoal'][0])
    {
        return $this->projectGoalUpdateGoalAsyncWithHttpInfo($project_id, $goal_id, $goal_request, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation projectGoalUpdateGoalAsyncWithHttpInfo
     *
     * Update goal
     *
     * @param  int $project_id (required)
     * @param  int $goal_id (required)
     * @param  \Hallerweb\Prioritize\Client\Model\GoalRequest $goal_request (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['projectGoalUpdateGoal'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function projectGoalUpdateGoalAsyncWithHttpInfo($project_id, $goal_id, $goal_request, string $contentType = self::contentTypes['projectGoalUpdateGoal'][0])
    {
        $returnType = '\Hallerweb\Prioritize\Client\Model\ProjectGoalDTO';
        $request = $this->projectGoalUpdateGoalRequest($project_id, $goal_id, $goal_request, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'projectGoalUpdateGoal'
     *
     * @param  int $project_id (required)
     * @param  int $goal_id (required)
     * @param  \Hallerweb\Prioritize\Client\Model\GoalRequest $goal_request (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['projectGoalUpdateGoal'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function projectGoalUpdateGoalRequest($project_id, $goal_id, $goal_request, string $contentType = self::contentTypes['projectGoalUpdateGoal'][0])
    {

        // verify the required parameter 'project_id' is set
        if ($project_id === null || (is_array($project_id) && count($project_id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $project_id when calling projectGoalUpdateGoal'
            );
        }

        // verify the required parameter 'goal_id' is set
        if ($goal_id === null || (is_array($goal_id) && count($goal_id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $goal_id when calling projectGoalUpdateGoal'
            );
        }

        // verify the required parameter 'goal_request' is set
        if ($goal_request === null || (is_array($goal_request) && count($goal_request) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $goal_request when calling projectGoalUpdateGoal'
            );
        }


        $resourcePath = '/api/v1/projects/{projectId}/goals/{goalId}';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;



        // path params
        if ($project_id !== null) {
            $resourcePath = str_replace(
                '{' . 'projectId' . '}',
                ObjectSerializer::toPathValue($project_id),
                $resourcePath
            );
        }
        // path params
        if ($goal_id !== null) {
            $resourcePath = str_replace(
                '{' . 'goalId' . '}',
                ObjectSerializer::toPathValue($goal_id),
                $resourcePath
            );
        }


        $headers = $this->headerSelector->selectHeaders(
            ['*/*', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (isset($goal_request)) {
            if (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the body
                $httpBody = \GuzzleHttp\Utils::jsonEncode(ObjectSerializer::sanitizeForSerialization($goal_request));
            } else {
                $httpBody = $goal_request;
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires HTTP basic authentication
        if (!empty($this->config->getUsername()) || !(empty($this->config->getPassword()))) {
            $headers['Authorization'] = 'Basic ' . base64_encode($this->config->getUsername() . ":" . $this->config->getPassword());
        }
        // this endpoint requires Bearer (JWT) authentication (access token)
        if (!empty($this->config->getAccessToken())) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'PATCH',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Create http client option
     *
     * @throws \RuntimeException on file opening failure
     * @return array of http client options
     */
    protected function createHttpClientOption()
    {
        $options = [];
        if ($this->config->getDebug()) {
            $options[RequestOptions::DEBUG] = fopen($this->config->getDebugFile(), 'a');
            if (!$options[RequestOptions::DEBUG]) {
                throw new \RuntimeException('Failed to open the debug file: ' . $this->config->getDebugFile());
            }
        }

        return $options;
    }
}
